import { Camera, Route, Users } from "lucide-react";

export type Lang = "id" | "en";

export const copy = {
  en: {
    nav: ["Platform", "Solutions", "Industries", "About"],
    talk: "Talk to our team",
    eyebrow: "INTEGRATED IoT · DATA · AI PLATFORM",
    heroA: "One connected system", heroB: "for every operation", heroC: "in motion.",
    heroText: "Treffix brings fleet, workforce, warehouse, and operational data together. Your team can see what is happening and make smarter decisions faster.",
    explore: "Explore solutions", industriesExplore: "Explore industries", heroProof: "Built for connected operations", live: "OPERATIONS OVERVIEW", online: "Concept preview", activity: "Sample signals", activityValue: "Concept", fleet: "Fleet activity", today: "Illustrative overview", vehicles: "Vehicles registered", coverage: "Nationwide coverage", network: "Connected network", signal: "Sample signal", updated: "Illustrative status", previewTag: "CONCEPT", monitor: "CONCEPT PREVIEW", mapLabel: "Illustrative fleet view · Indonesia", trust: "BUILT FOR OPERATIONS THAT NEVER STAND STILL", openMenu: "Open navigation", closeMenu: "Close navigation", primaryNav: "Main navigation", switchLanguage: "Choose language", homeLabel: "Treffix home", skipToContent: "Skip to main content",
    aboutEyebrow: "THE TREFFIX APPROACH", aboutTitle: "Technology that connects the way your business works.", aboutText: "Operations rarely happen in one place. Treffix brings the signals, systems, and people behind your business into one connected view, helping information move as quickly as your work does.", quote: "We don’t just digitize operations. We connect them.", atGlance: "Treffix at a glance", founded: "Established", solutions: "Connected solutions", coverageStat: "Technical coverage",
    solutionsEyebrow: "ONE PLATFORM. MANY POSSIBILITIES.", solutionsTitle: "Tools that work better together.", solutionsText: "Start with the operational challenge in front of you. Connect more of your business as your needs grow.", track: "Fleet management", work: "Employee & workforce management", sight: "AI CCTV", learnMore: "Explore solution", capabilities: "WHAT IT HELPS YOU DO", industriesLabel: "Built for",
    ecosystemEyebrow: "THE CONNECTED OPERATING LAYER", ecosystemTitle: "When your data moves together, your business moves forward.", ecosystemText: "Treffix brings day-to-day activity into one operational intelligence layer. It turns fragmented signals into shared context, timely alerts, and clearer decisions.", storySteps: [{ label: "01 · CONNECT", title: "Bring every signal together", body: "Connect fleet, workforce, warehouse, and order data in one shared view." }, { label: "02 · UNDERSTAND", title: "See what needs attention", body: "Timely alerts help teams spot exceptions and understand what is changing across operations." }, { label: "03 · ACT", title: "Move from insight to action", body: "Give every team the context to coordinate next steps and keep work moving." }], orders: "Orders", warehouse: "Warehouse", fleetNode: "Fleet", workforce: "Workforce", intelligence: "TREFFIX INTELLIGENCE", insights: "Insights & action", decisions: "Better informed decisions",
    industriesEyebrow: "MADE FOR THE FIELD", industriesTitle: "Designed around the realities of your operation.", industriesText: "From the first mile to the last shift, connect the people and assets that keep your business moving.", logistics: "Logistics & distribution", logisticsText: "Keep deliveries, vehicles, and operating costs in view. That way, your team can address exceptions before they cause delays.", mobility: "Transportation & mobility", mobilityText: "Coordinate vehicles and teams with live visibility across routes and daily operations.", mining: "Mining & heavy equipment", miningText: "Understand asset activity, site movement, and equipment utilization in demanding environments.", needs: ["Live asset visibility", "Route & activity insights", "Exception alerts"],
    proofEyebrow: "SEE OPERATIONS AS THEY HAPPEN", proofTitle: "One view. A clearer next move.", proofText: "Bring the details that matter into one operational picture, including vehicle status, route activity, and updates from your teams and facilities.", activeVehicles: "Registered vehicles", attention: "Needs attention", activityTitle: "Operational activity", onRoute: "Route activity", fleetStatus: "Fleet status", operational: "Illustrative dashboard concept",
    storiesEyebrow: "BUILT AROUND REAL WORK", storiesTitle: "Technology shaped by operational challenges.", storiesText: "Every operation is different. Treffix works with teams to connect the right signals, workflows, and tools to the work they need to do.", storyName: "FIXTRACK", storyType: "SOLUTION SPOTLIGHT · FLEET INTELLIGENCE", storyTitle: "A clearer view of every route.", storyDesc: "Bring live fleet location, geofencing, driver safety signals, and route activity into one operational view with FixTrack.", storyTag: "Solution spotlight", storyLink: "Discover FixTrack",
    whyEyebrow: "WHY TREFFIX", whyTitle: "Practical technology. Connected thinking.", whyText: "Make complex operations easier to understand, coordinate, and improve.", why: ["Built around your workflow", "Connected by design", "Real-time by default", "Ready for intelligence", "Supported nationwide"], whyDesc: ["Technology that adapts to the realities of how your team works.", "Bring fleet, people, warehouse, orders, and data into one ecosystem.", "See what is happening across the field, fleet, and facility as it happens.", "Build a foundation for automation, prediction, and AI-led action.", "Dependable implementation and field support across Indonesia."],
    faqEyebrow: "GOOD TO KNOW", faqTitle: "A few things you might be wondering.", faq: [["What is Treffix?", "Treffix is an Indonesian IoT, data, and AI company that connects operational systems, assets, and teams to help businesses make better informed decisions."], ["Which industries does Treffix serve?", "Treffix works with logistics and distribution, transportation and mobility, mining and heavy equipment, warehouse operations, and other businesses with connected field operations."], ["Can the solutions work together?", "Yes. FixTrack, FixWork, FixHub, and OCS can be combined so operational signals move across teams and workflows."], ["Can Treffix integrate with existing systems?", "Integration needs depend on your current systems and operational requirements. The Treffix team can discuss the right approach for your environment."], ["How do I get started?", "Tell the Treffix team about your operation and the challenge you want to solve. They can help identify a suitable solution and next steps."]],
    ctaEyebrow: "LET’S CONNECT THE DOTS", ctaTitle: "Make every operational decision more informed.", ctaText: "Explore how connected visibility and timely operational signals can help your business move with more confidence.", ctaButton: "Start a conversation", contactNote: "A clearer operation starts with a good conversation.", fallbackCta: "Explore solutions", fallbackNote: "Explore the Treffix solutions and see where connected operations can help.", footerText: "The connected operating layer for businesses in motion.", footerNav: "Explore", contact: "Contact", rights: "© 2026 Treffix. All rights reserved.", language: "Bahasa Indonesia",
  },
  id: {
    nav: ["Platform", "Solusi", "Industri", "Tentang"],
    talk: "Hubungi tim kami",
    eyebrow: "PLATFORM TERINTEGRASI IoT · DATA · AI",
    heroA: "Satu sistem terhubung", heroB: "untuk setiap operasional", heroC: "yang terus bergerak.",
    heroText: "Treffix menghubungkan armada, tenaga kerja, gudang, dan data operasional agar tim Anda memahami situasi dan mengambil keputusan lebih cepat.",
    explore: "Jelajahi solusi", industriesExplore: "Jelajahi industri", heroProof: "Dirancang untuk operasional terhubung", live: "RINGKASAN OPERASIONAL", online: "Pratinjau konsep", activity: "Sinyal contoh", activityValue: "Konsep", fleet: "Aktivitas armada", today: "Ringkasan ilustratif", vehicles: "Kendaraan terdaftar", coverage: "Jangkauan nasional", network: "Jaringan terhubung", signal: "Sinyal contoh", updated: "Status ilustratif", previewTag: "KONSEP", monitor: "PRATINJAU KONSEP", mapLabel: "Ilustrasi armada · Indonesia", trust: "UNTUK OPERASIONAL YANG TERUS BERGERAK", openMenu: "Buka navigasi", closeMenu: "Tutup navigasi", primaryNav: "Navigasi utama", switchLanguage: "Pilih bahasa", homeLabel: "Halaman utama Treffix", skipToContent: "Langsung ke konten utama",
    aboutEyebrow: "PENDEKATAN TREFFIX", aboutTitle: "Teknologi yang menghubungkan cara bisnis Anda bekerja.", aboutText: "Operasional jarang terjadi hanya di satu tempat. Treffix menyatukan sinyal, sistem, dan orang-orang di balik bisnis Anda agar informasi bergerak secepat pekerjaan.", quote: "Kami tidak hanya mendigitalisasi operasional. Kami menghubungkannya.", atGlance: "Sekilas tentang Treffix", founded: "Berdiri", solutions: "Solusi terhubung", coverageStat: "Jangkauan teknis",
    solutionsEyebrow: "SATU PLATFORM. BANYAK KEMUNGKINAN.", solutionsTitle: "Solusi yang bekerja lebih baik bersama.", solutionsText: "Mulai dari tantangan operasional yang dihadapi. Hubungkan lebih banyak bagian bisnis seiring kebutuhan berkembang.", track: "Manajemen armada", work: "Manajemen karyawan & tenaga kerja", sight: "CCTV berbasis AI", learnMore: "Jelajahi solusi", capabilities: "YANG DAPAT DILAKUKAN", industriesLabel: "Dirancang untuk",
    ecosystemEyebrow: "LAPISAN OPERASIONAL TERHUBUNG", ecosystemTitle: "Saat data bergerak bersama, bisnis melangkah maju.", ecosystemText: "Treffix menyatukan aktivitas harian dalam satu lapisan intelijen operasional. Lapisan ini mengubah sinyal yang terpisah menjadi konteks bersama, peringatan tepat waktu, dan keputusan yang lebih terarah.", storySteps: [{ label: "01 · HUBUNGKAN", title: "Satukan setiap sinyal", body: "Hubungkan data armada, tenaga kerja, gudang, dan pesanan dalam satu tampilan bersama." }, { label: "02 · PAHAMI", title: "Kenali hal yang perlu ditangani", body: "Peringatan tepat waktu membantu tim melihat kendala dan memahami perubahan operasional." }, { label: "03 · BERTINDAK", title: "Ubah insight menjadi tindakan", body: "Berikan konteks yang dibutuhkan setiap tim untuk menyelaraskan langkah dan menjaga pekerjaan tetap berjalan." }], orders: "Pesanan", warehouse: "Gudang", fleetNode: "Armada", workforce: "Tenaga kerja", intelligence: "INTELIJEN TREFFIX", insights: "Insight & tindakan", decisions: "Keputusan lebih terarah",
    industriesEyebrow: "DIRANCANG UNTUK LAPANGAN", industriesTitle: "Memahami realitas operasional Anda.", industriesText: "Dari perjalanan pertama hingga pergantian shift terakhir, hubungkan orang dan aset yang menjaga bisnis terus bergerak.", logistics: "Logistik & distribusi", logisticsText: "Pantau pengiriman, kendaraan, dan biaya operasional sebelum kendala menjadi keterlambatan.", mobility: "Transportasi & mobilitas", mobilityText: "Koordinasikan kendaraan dan tim melalui visibilitas rute serta aktivitas harian secara langsung.", mining: "Pertambangan & alat berat", miningText: "Pahami aktivitas aset, pergerakan di lokasi, dan pemanfaatan alat di lingkungan kerja yang menantang.", needs: ["Visibilitas aset langsung", "Insight rute & aktivitas", "Peringatan kendala"],
    proofEyebrow: "LIHAT OPERASIONAL SAAT BERLANGSUNG", proofTitle: "Satu tampilan. Langkah berikutnya lebih jelas.", proofText: "Satukan detail penting dalam satu gambaran operasional, mulai dari status kendaraan dan aktivitas rute hingga informasi dari tim dan fasilitas.", activeVehicles: "Kendaraan terdaftar", attention: "Perlu perhatian", activityTitle: "Aktivitas operasional", onRoute: "Aktivitas rute", fleetStatus: "Status armada", operational: "Konsep dashboard ilustratif",
    storiesEyebrow: "BERANGKAT DARI KEBUTUHAN NYATA", storiesTitle: "Teknologi yang dibentuk oleh tantangan operasional.", storiesText: "Setiap operasional punya kebutuhan berbeda. Treffix bekerja bersama tim untuk menghubungkan sinyal, alur kerja, dan perangkat yang tepat.", storyName: "FIXTRACK", storyType: "SOROTAN SOLUSI · INTELIJEN ARMADA", storyTitle: "Gambaran yang lebih jelas untuk setiap rute.", storyDesc: "Satukan lokasi armada langsung, geofence, sinyal keselamatan pengemudi, dan aktivitas rute ke dalam satu tampilan operasional dengan FixTrack.", storyTag: "Sorotan solusi", storyLink: "Kenali FixTrack",
    whyEyebrow: "MENGAPA TREFFIX", whyTitle: "Teknologi praktis. Cara berpikir terhubung.", whyText: "Permudah operasional kompleks agar lebih mudah dipahami, dikoordinasikan, dan ditingkatkan.", why: ["Dirancang untuk alur kerja Anda", "Terhubung sejak awal", "Data langsung", "Siap untuk intelijen", "Dukungan nasional"], whyDesc: ["Teknologi yang menyesuaikan realitas cara tim Anda bekerja.", "Hubungkan armada, orang, gudang, pesanan, dan data dalam satu ekosistem.", "Lihat situasi di lapangan, armada, dan fasilitas saat terjadi.", "Bangun fondasi untuk otomasi, prediksi, dan tindakan berbasis AI.", "Implementasi dan dukungan lapangan yang dapat diandalkan di Indonesia."],
    faqEyebrow: "INFORMASI TAMBAHAN", faqTitle: "Pertanyaan yang mungkin Anda pikirkan.", faq: [["Apa itu Treffix?", "Treffix adalah perusahaan IoT, data, dan AI di Indonesia yang menghubungkan sistem operasional, aset, dan tim agar bisnis dapat mengambil keputusan lebih terarah."], ["Industri apa saja yang dilayani Treffix?", "Treffix bekerja dengan industri logistik dan distribusi, transportasi dan mobilitas, pertambangan dan alat berat, pergudangan, serta bisnis lain dengan operasional lapangan terhubung."], ["Apakah setiap solusi dapat digunakan bersama?", "Ya. FixTrack, FixWork, FixHub, dan OCS dapat digabungkan agar sinyal operasional mengalir di antara tim dan alur kerja."], ["Bisakah Treffix terhubung dengan sistem yang sudah ada?", "Kebutuhan integrasi bergantung pada sistem dan kebutuhan operasional Anda. Tim Treffix dapat mendiskusikan pendekatan yang sesuai."], ["Bagaimana cara memulai?", "Ceritakan operasional dan tantangan yang ingin Anda selesaikan kepada tim Treffix. Mereka dapat membantu menentukan solusi dan langkah berikutnya." ]],
    ctaEyebrow: "MARI HUBUNGKAN SEMUANYA", ctaTitle: "Ambil keputusan operasional dengan lebih yakin.", ctaText: "Jelajahi bagaimana visibilitas terhubung dan sinyal operasional tepat waktu membantu bisnis bergerak dengan lebih percaya diri.", ctaButton: "Mulai percakapan", contactNote: "Operasional yang lebih jelas dimulai dari percakapan yang baik.", fallbackCta: "Jelajahi solusi", fallbackNote: "Jelajahi solusi Treffix dan lihat bagaimana operasional terhubung dapat membantu.", footerText: "Lapisan operasional terhubung untuk bisnis yang terus bergerak.", footerNav: "Jelajahi", contact: "Kontak", rights: "© 2026 Treffix. Hak cipta dilindungi.", language: "English",
  },
};

export const products = [
  { id: "FixTrack", icon: Route, logo: "/fixtrack-icon-blue.svg", title: { en: "Track every movement. Optimize every mile.", id: "Pantau setiap pergerakan. Optimalkan setiap perjalanan." }, desc: { en: "Know where every vehicle is, what it is doing, and where action is needed next.", id: "Ketahui posisi kendaraan, aktivitasnya, dan langkah yang perlu dilakukan berikutnya." }, points: { en: ["Live fleet map and geofencing", "Driver behavior and safety alerts", "Asset utilization and route insights", "Optional AI DashCam"], id: ["Peta armada dan geofence langsung", "Peringatan perilaku dan keselamatan pengemudi", "Pemanfaatan aset dan insight rute", "AI DashCam opsional"] }, industry: { en: "Logistics · Transportation · Mining", id: "Logistik · Transportasi · Pertambangan" } },
  { id: "FixWork", icon: Users, logo: "/fixwork-white.svg", title: { en: "Bring your field teams into view.", id: "Hubungkan tim lapangan Anda." }, desc: { en: "Coordinate people, attendance, and field activity with a clearer view of daily work.", id: "Koordinasikan orang, kehadiran, dan aktivitas lapangan dengan gambaran kerja harian yang lebih jelas." }, points: { en: ["Workforce location and attendance", "Field task coordination", "Operational activity monitoring", "Team performance visibility"], id: ["Lokasi dan kehadiran tenaga kerja", "Koordinasi tugas lapangan", "Pemantauan aktivitas operasional", "Visibilitas kinerja tim"] }, industry: { en: "Field services · Logistics · Mining", id: "Layanan lapangan · Logistik · Pertambangan" } },
  { id: "FixSight", icon: Camera, logo: undefined, title: { en: "AI CCTV monitoring.", id: "Pemantauan CCTV berbasis AI." }, desc: { en: "Turn camera feeds into useful alerts.", id: "Ubah rekaman kamera menjadi peringatan yang berguna." }, points: { en: ["AI CCTV", "Camera feed monitoring", "Useful alerts"], id: ["CCTV berbasis AI", "Pemantauan rekaman kamera", "Peringatan yang berguna"] }, industry: { en: "Camera monitoring", id: "Pemantauan kamera" } },
] as const;
export type Copy = typeof copy[Lang];


