import { Camera, Route, Users } from "lucide-react";

export type Lang = "id" | "en";

export const copy = {
  en: {
    nav: ["Solutions", "Industries", "About", "Blog"],
    talk: "Talk to our team",
    eyebrow: "BUILT FOR BETTER BUSINESS OPERATIONS",
    heroA: "Run your business operations with", heroB: "greater clarity and control.",
    heroText: "Treffix helps businesses improve operational efficiency, connect teams, and simplify everyday workflows with intelligent digital solutions built for real-world work.",
    explore: "Explore products", industriesExplore: "Explore industries", heroProof: "Three focused products", coverage: "Nationwide coverage", network: "Connected network", trust: "BUILT FOR OPERATIONS THAT NEVER STAND STILL", openMenu: "Open navigation", closeMenu: "Close navigation", primaryNav: "Main navigation", switchLanguage: "Choose language", homeLabel: "Treffix home", skipToContent: "Skip to main content",
    aboutEyebrow: "ABOUT TREFFIX", aboutTitle: "Digital solutions for fleet tracking, workforce management, and operational monitoring.", aboutText: "Treffix provides digital solutions to help businesses manage operations more efficiently and stay connected.", aboutPartnerPlaceholder: "Partner logo placeholders — replace with approved wordmarks before publication.",
    solutionsEyebrow: "THREE TREFFIX PRODUCTS", solutionsTitle: "Digital Solutions for More Efficient\nand Connected Business Operations", solutionsText: "Choose fleet and vehicle tracking, HRMS and workforce management, or AI CCTV camera monitoring with PPE detection.", track: "Fleet and vehicle tracking", work: "HRMS and workforce management", sight: "AI CCTV camera monitoring and PPE detection", industriesLabel: "Built for",
    ecosystemEyebrow: "THREE TREFFIX PRODUCTS", ecosystemTitle: "Fleet tracking, HRMS, and AI CCTV for operational teams.", ecosystemText: "FixTrack tracks fleets and vehicles. FixWork supports HRMS and workforce management. FixSight AI CCTV monitors cameras and workplace activity, including PPE use.", storySteps: [{ label: "01 · FIXTRACK · FLEET TRACKING", title: "Fleet tracking for vehicles and journeys", body: "Start with the fleet: track vehicle locations in real time and review journeys with FixTrack." }, { label: "02 · FIXSIGHT · AI CCTV", title: "AI CCTV for workplace activity and productivity", body: "Next, FixSight AI CCTV monitors workplace activity, employee productivity, and PPE use." }, { label: "03 · FIXWORK · HRMS", title: "HRMS for employee management", body: "For your team, manage attendance, recruitment, employee records, OCR onboarding, approvals, and payroll with FixWork." }], decisions: "Explore Treffix operational solutions",
    industriesEyebrow: "MADE FOR THE FIELD", industriesTitle: "Designed around the realities of your operation.", industriesText: "See how vehicle tracking applies across logistics, transportation, and mining operations.", logistics: "Logistics & distribution", logisticsText: "Track fleet vehicles across logistics and distribution operations.", mobility: "Transportation & mobility", mobilityText: "Track vehicle locations across transportation and mobility operations.", mining: "Mining & heavy equipment", miningText: "Track vehicles across mining and heavy-equipment sites.", needs: ["Fleet tracking", "Vehicle location tracking", "Vehicle movement visibility"],whyEyebrow: "THE TREFFIX PRODUCTS", whyTitle: "Tools for fleet, workforce, and camera monitoring.", whyText: "Each product addresses a different operational need.", why: ["FixTrack", "FixWork", "FixSight AI CCTV"], whyDesc: ["Fleet and vehicle tracking.", "HRMS and workforce management.", "Camera monitoring and PPE detection."],
    faqEyebrow: "GOOD TO KNOW", faqTitle: "A few things you might be wondering.", faq: [["What products does Treffix offer?", "FixTrack is for fleet and vehicle tracking, FixWork is for HRMS and workforce management, and FixSight AI CCTV is for camera monitoring and PPE detection."], ["Which industries does Treffix serve?", "Treffix serves logistics and distribution, transportation and mobility, and mining and heavy-equipment operations."], ["What does FixSight AI CCTV do?", "It monitors camera feeds and detects PPE."], ["Can Treffix integrate with existing systems?", "Integration needs depend on your current systems and operational requirements. The Treffix team can discuss the right approach for your environment."], ["How do I get started?", "Tell the Treffix team about your operation and the challenge you want to solve. They can help identify a suitable product and next steps."]],
    blogEyebrow: "LATEST ARTICLES", blogTitle: "Insights to help shape the future of your industry.", blogText: "Explore practical guides to fleet tracking, operational monitoring with AI CCTV, and workforce management.", blogRead: "Read article", blogBack: "Back to articles", blogViewAll: "View all articles",
    ctaEyebrow: "TALK TO THE TREFFIX TEAM", ctaTitle: "Find the product that fits your operation.", ctaText: "Ask about FixTrack for fleet tracking, FixWork for HRMS and workforce management, or FixSight AI CCTV for camera monitoring and PPE detection.", ctaButton: "Start a conversation", contactNote: "Tell us about your operational needs.", fallbackCta: "Explore products", fallbackNote: "Compare fleet tracking, HRMS and workforce management, and AI CCTV camera monitoring with PPE detection.", footerText: "Products for fleet tracking, workforce management, and camera monitoring.", footerNav: "Explore", contact: "Contact", rights: "© 2026 Treffix. All rights reserved.", language: "Bahasa Indonesia",
  },
  id: {
    nav: ["Solusi", "Industri", "Tentang", "Artikel"],
    talk: "Hubungi tim kami",
    eyebrow: "DIRANCANG UNTUK OPERASIONAL BISNIS YANG LEBIH BAIK",
    heroA: "Kelola operasional bisnis dengan", heroB: "lebih mudah dan terarah.",
    heroText: "Treffix membantu bisnis meningkatkan efisiensi operasional, menyelaraskan kerja tim, dan menyederhanakan proses harian melalui solusi digital cerdas yang dirancang untuk kebutuhan nyata.",
    explore: "Jelajahi produk", industriesExplore: "Jelajahi industri", heroProof: "Tiga produk dengan fungsi jelas", coverage: "Jangkauan nasional", network: "Jaringan terhubung", trust: "UNTUK OPERASIONAL YANG TERUS BERGERAK", openMenu: "Buka navigasi", closeMenu: "Tutup navigasi", primaryNav: "Navigasi utama", switchLanguage: "Pilih bahasa", homeLabel: "Halaman utama Treffix", skipToContent: "Langsung ke konten utama",
    aboutEyebrow: "TENTANG TREFFIX", aboutTitle: "Solusi digital untuk pelacakan armada, manajemen tenaga kerja, dan pemantauan operasional.", aboutText: "Treffix menghadirkan solusi digital untuk membantu bisnis mengelola operasional dengan lebih efisien dan terhubung.", aboutPartnerPlaceholder: "Placeholder logo mitra — ganti dengan wordmark resmi sebelum dipublikasikan.",
    solutionsEyebrow: "TIGA PRODUK TREFFIX", solutionsTitle: "Solusi Digital untuk Operasional Bisnis\nyang Lebih Efisien dan Terintegrasi", solutionsText: "Pilih pelacakan armada dan kendaraan, HRMS dan manajemen tenaga kerja, atau CCTV AI untuk pemantauan kamera dan deteksi APD.", track: "Pelacakan armada dan kendaraan", work: "HRMS dan manajemen tenaga kerja", sight: "Pemantauan kamera CCTV AI dan deteksi APD", industriesLabel: "Dirancang untuk",
    ecosystemEyebrow: "SOLUSI DIGITAL UNTUK OPERASIONAL BISNIS", ecosystemTitle: "Tiga solusi digital untuk pelacakan armada, HRMS, dan CCTV AI.", ecosystemText: "Treffix menghadirkan FixTrack untuk pelacakan armada dan kendaraan, FixWork untuk HRMS dan manajemen tenaga kerja, serta FixSight AI CCTV untuk memantau kamera dan aktivitas kerja, termasuk penggunaan APD.", storySteps: [{ label: "01 · FIXTRACK · PELACAKAN ARMADA", title: "Pelacakan armada dan perjalanan kendaraan", body: "Mulai dari armada: pantau lokasi kendaraan secara real-time dan tinjau perjalanan dengan FixTrack." }, { label: "02 · FIXSIGHT · CCTV AI", title: "CCTV AI untuk aktivitas dan produktivitas kerja", body: "Lanjutkan ke area kerja: FixSight AI CCTV memantau aktivitas, produktivitas karyawan, dan penggunaan APD." }, { label: "03 · FIXWORK · HRMS", title: "HRMS untuk pengelolaan karyawan", body: "Untuk tim Anda, kelola absensi, rekrutmen, data karyawan, onboarding OCR, persetujuan, dan payroll melalui FixWork." }], decisions: "Jelajahi solusi operasional Treffix",
    industriesEyebrow: "DIRANCANG UNTUK LAPANGAN", industriesTitle: "Memahami realitas operasional Anda.", industriesText: "Lihat penggunaan pelacakan kendaraan di operasional logistik, transportasi, dan pertambangan.", logistics: "Logistik & distribusi", logisticsText: "Lacak kendaraan armada dalam operasional logistik dan distribusi.", mobility: "Transportasi & mobilitas", mobilityText: "Lacak lokasi kendaraan dalam operasional transportasi dan mobilitas.", mining: "Pertambangan & alat berat", miningText: "Lacak kendaraan di lokasi pertambangan dan operasional alat berat.", needs: ["Pelacakan armada", "Pelacakan lokasi kendaraan", "Visibilitas pergerakan kendaraan"],whyEyebrow: "PRODUK TREFFIX", whyTitle: "Perangkat untuk armada, tenaga kerja, dan pemantauan kamera.", whyText: "Setiap produk menangani kebutuhan operasional yang berbeda.", why: ["FixTrack", "FixWork", "FixSight AI CCTV"], whyDesc: ["Pelacakan armada dan kendaraan.", "HRMS dan manajemen tenaga kerja.", "Pemantauan kamera dan deteksi APD."],
    faqEyebrow: "INFORMASI TAMBAHAN", faqTitle: "Pertanyaan yang mungkin Anda pikirkan.", faq: [["Produk apa saja yang ditawarkan Treffix?", "FixTrack untuk pelacakan armada dan kendaraan, FixWork untuk HRMS dan manajemen tenaga kerja, serta FixSight AI CCTV untuk pemantauan kamera dan deteksi APD."], ["Industri apa saja yang dilayani Treffix?", "Treffix melayani logistik dan distribusi, transportasi dan mobilitas, serta pertambangan dan operasional alat berat."], ["Apa fungsi FixSight AI CCTV?", "FixSight AI CCTV memantau kamera dan mendeteksi APD."], ["Bisakah Treffix terhubung dengan sistem yang sudah ada?", "Kebutuhan integrasi bergantung pada sistem dan kebutuhan operasional Anda. Tim Treffix dapat mendiskusikan pendekatan yang sesuai."], ["Bagaimana cara memulai?", "Ceritakan operasional dan tantangan yang ingin Anda selesaikan kepada tim Treffix. Mereka dapat membantu menentukan produk dan langkah berikutnya."]],
    blogEyebrow: "ARTIKEL TERBARU", blogTitle: "Wawasan terbaru untuk membentuk masa depan industri Anda.", blogText: "Baca panduan tentang pelacakan armada, pemantauan operasional dengan CCTV AI, dan pengelolaan tenaga kerja.", blogRead: "Baca artikel", blogBack: "Kembali ke artikel", blogViewAll: "Lihat semua",
    ctaEyebrow: "HUBUNGI TIM TREFFIX", ctaTitle: "Temukan produk yang sesuai untuk operasional Anda.", ctaText: "Tanyakan tentang FixTrack untuk pelacakan armada, FixWork untuk HRMS dan manajemen tenaga kerja, atau FixSight AI CCTV untuk pemantauan kamera dan deteksi APD.", ctaButton: "Mulai percakapan", contactNote: "Ceritakan kebutuhan operasional Anda.", fallbackCta: "Jelajahi produk", fallbackNote: "Bandingkan pelacakan armada, HRMS dan manajemen tenaga kerja, serta CCTV AI untuk pemantauan kamera dan deteksi APD.", footerText: "Produk untuk pelacakan armada, manajemen tenaga kerja, dan pemantauan kamera.", footerNav: "Jelajahi", contact: "Kontak", rights: "© 2026 Treffix. Hak cipta dilindungi.", language: "English",
  },
};

export const products = [
  { id: "FixTrack", icon: Route, logo: "/fixtrack-icon-blue.svg", title: { en: { before: "", highlight: "Real-Time Fleet Tracking", after: " for More Efficient Operations" }, id: { before: "", highlight: "Pelacakan Armada Real-Time", after: " untuk Operasional yang Lebih Efisien" } }, desc: { en: "Track vehicle locations and status, review trips, and respond to issues faster with FixTrack fleet tracking software.", id: "Pantau lokasi dan status kendaraan, tinjau perjalanan, dan tanggapi kendala lebih cepat dengan sistem pelacakan armada FixTrack." }, points: { en: ["Real-time vehicle monitoring", "Real-time alerts", "Trip playback", "Order tracking", "In-vehicle dashcam", "Real-time vehicle status monitoring"], id: ["Pemantauan kendaraan real-time", "Notifikasi real-time", "Pemutaran ulang perjalanan", "Pelacakan pesanan", "Dashcam kendaraan", "Pemantauan status kendaraan secara real-time"] }, industry: { en: "Fleet operations", id: "Operasional armada" } },
  { id: "FixWork", icon: Users, logo: "/fixwork-blue.svg", title: { en: { before: "Simplify HR Management, from ", highlight: "Recruitment to Payroll", after: "" }, id: { before: "Kelola SDM Lebih Efisien, dari ", highlight: "Rekrutmen hingga Payroll", after: "" } }, desc: { en: "Manage attendance, recruitment, employee records, onboarding, approvals, and payroll in one HRMS platform.", id: "Sederhanakan absensi, rekrutmen, administrasi karyawan, onboarding, persetujuan, dan payroll dalam satu platform HRMS." }, points: { en: ["Face recognition & attendance zones", "Recruitment process management", "Employee administration", "Flexible approval workflows", "OCR-powered onboarding", "Payroll management"], id: ["Pengenalan wajah & area absensi", "Proses rekrutmen", "Administrasi kepegawaian", "Persetujuan fleksibel", "Onboarding dengan OCR", "Manajemen payroll"] }, industry: { en: "HR and workforce teams", id: "Tim HR dan tenaga kerja" } },
  { id: "FixSight", icon: Camera, logo: undefined, title: { en: { before: "Improve Workplace Safety with ", highlight: "AI CCTV Monitoring", after: "" }, id: { before: "Tingkatkan Keamanan dengan ", highlight: "Pemantauan CCTV AI", after: "" } }, desc: { en: "Monitor workspaces in real time, detect risks with AI, and gain insights to support safer, more productive operations.", id: "Pantau area kerja secara real-time, deteksi risiko dengan AI, dan dapatkan insight untuk mendukung tempat kerja yang lebih aman dan produktif." }, points: { en: ["Real-time CCTV monitoring", "CCTV video playback", "Real-time alerts", "AI detection", "Employee productivity monitoring", "Real-time insights dashboard"], id: ["Pemantauan CCTV real-time", "Pemutaran ulang video CCTV", "Notifikasi real-time", "Deteksi AI", "Pemantauan produktivitas karyawan", "Dashboard insight real-time"] }, industry: { en: "Sites using AI CCTV", id: "Lokasi dengan CCTV AI" } },
] as const;
export type Copy = typeof copy[Lang];


